### ISSUE TITLE
Interesting demos

### ISSUE THREAD

**Issue by btknu** [susam/cfr#1]
Follow up to the request in [Demos](https://github.com/susam/cfr#demos), I'm creating an issue with interesting examples. I'll group a couple in a single issue.

1: https://susam.net/cfr.html#B14F2C2F2E5RB5FEB4F2EFE3RE2RE3BCE3R4ER2E

2: https://susam.net/cfr.html#B3RB2CBRB2F17B3RB4FE5B4FE2FE4RE3RE5

3: https://susam.net/cfr.html#B3CBCBCB10FE5B3RB4F2RF2E7REB2RE4RE3RFE4

4: https://susam.net/cfr.html#B2CB14FE8B3FRB4FE6REB2RE4RE4RCFCRE2

5: https://susam.net/cfr.html#B16FE8B3FRB4FRFE6REB2RE4RE4RC2FE2

6: https://susam.net/cfr.html#B17FE8RE2B6FE7RFE3FE2C2E

7: https://susam.net/cfr.html#B21FE2B3RFE7RE6RE3RECERFECEFRE

**Comment by btknu** [comment]
And more:

1. https://susam.net/cfr.html#B17CFC7FE6BRE3BCFC7FE5R2E2RE3
2. https://susam.net/cfr.html#B17F2E6BRE3BF2E5R2E2RE3
3. https://susam.net/cfr.html#B19FE7R2FR2ER2F2R6E7R4FE
4. https://susam.net/cfr.html#RB16FE7R2FR2ER2F2R2CR4E7R4FE

**Comment by susam** [comment]
@btknu These demos are beautiful!  Thank you for experimenting with this project and sharing these demos.

I would like to include the following three demos to the built-in list of demos if you permit me to do so:

* https://susam.net/cfr.html#B3RB2CBRB2F17B3RB4FE5B4FE2FE4RE3RE5
* https://susam.net/cfr.html#B17FE8RE2B6FE7RFE3FE2C2E
* https://susam.net/cfr.html#B17F2E6BRE3BF2E5R2E2RE3

These demos will become part of the CFR[] implementation code and will be available to everyone under the terms of the MIT license.  My plan is to make them available as demo numbers 900, 901, and 902.  Please let me know what you think.  Also, please let me know what name of yours I should use while crediting these demos to you.  Should I credit these to `btknu` or would you prefer your complete name or another name in the credits?  You are also very welcome to send a pull request for this but it isn't necessary.  I can add these to the demo list myself (under the terms of the MIT license) if you permit me to do so.

**Comment by susam** [comment]
By the way, I have extended CFR[] to create CFRS[] which is available at https://susam.net/cfrs.html and https://github.com/susam/cfrs.  This extension supports the `S` command that can be used to make the turtle sleep for 20 ms.  This command may be used to produce animation effects.  If you try it out and come up with interesting demos, please do share.

**Comment by btknu** [comment]
Thank you! And yes, I’d be happy to see these demos added to the repo, under the MIT license 👍

Here are some more:

- https://susam.net/cfrs.html#B6F2CFB2R7B3FE2SE2F4R4FEC7R3F3E3RE3
- https://susam.net/cfrs.html#CB4RBRBRB3FESERCFC4FC2F2CF6R7EF2C4EC4FRE4
- https://susam.net/cfrs.html#CB9RBSB3FE2CF2C2F2C2FC3F7E3RE2RER2FRE3FR2EF2R2E

Feel free to add these to cfr/cfrs repo under MIT license as well if you want.

Congrats on the project, it’s a joy to use.

**Comment by btknu** [comment]
I’ve forgotten to answer the question about crediting; “btknu” is good and thanks for asking.

**Comment by btknu** [comment]
One more: https://susam.net/cfrs.html#B3R3BRBRB2C2B2FESEC6RER6EF2EFREC7B3FSF2RE3CE3

**Comment by susam** [comment]
The demos are now available in its own page at <https://susam.github.io/cfrs/demo.html>. Thank you for the wonderful demos!
