### ISSUE TITLE
Demo Patterns

### ISSUE THREAD

**Issue by MystPi** [susam/cfr#2]
I have stumbled upon two quite interesting patterns which seem fit for the demo request.
- https://susam.net/cfr.html#B10FE4RE2R2E2R2C2E2
- https://susam.net/cfr.html#B11FB3FE4R2FR2B4FE4BR3EFBR3E4RE3R2E2

Here are screenshots:
![image](https://github.com/susam/cfr/assets/86574651/f9a33fae-f2d8-40df-8ee5-0ec34751c54c)
![image](https://github.com/susam/cfr/assets/86574651/f8ec636a-d9a3-4217-a5fc-f40408de7c73)

**Comment by susam** [comment]
@MystPi These are wonderful demos!  Thanks for sharing.  I'd like to add the second demo to the built-in list of demos as demo number 903 or something close to that.  The demo will then be available to everyone under the terms of the MIT license.  Does this sound okay to you?  If so, would you like me to use any specific name of yours while crediting this demo to you or should I just credit this to `MystPi`?

By the way, there is now an extension of this project called CFRS[].  This extension supports an additional command named `S` that makes the turtle sleep for 20 ms.  It can be used to produce animation effects.  CFRS[] is available at https://susam.net/cfrs.html and https://github.com/susam/cfrs.

**Comment by MystPi** [comment]
Thank you very much! Yes, that sounds great to me. No credit is necessary, but if you do end up adding it, `MystPi` is what I prefer to be referenced as.

As for the new command/site, wow, so cool! It really helps clarify what's going on in a complex program. Thank you for sharing it.

**Comment by susam** [comment]
Thank you! The demos are now available in its own page at <https://susam.github.io/cfrs/demo.html>.
