### ISSUE TITLE
Fractal experiments

### ISSUE THREAD

**Issue by aartaka** [susam/cfr#3]
I was mainly trying to make [Dragon Curve](https://en.wikipedia.org/wiki/Dragon_curve) in CFRS, but I've no success so far. These are by-products of my attempts:

- Picasso tiles https://susam.net/cfrs.html#B8F16EC2REC2REC2REC2REC2EC2EC2RE
- Hexagon tiles https://susam.net/cfrs.html#B5R2FRECBRF37E5
- Pyrite https://susam.net/cfrs.html#C7BRB2RBEFRFBFB2FBFBF2EF2EF2BF3EFBFEFER2EFEFRF2E2F5E
- Another alien flower https://susam.net/cfrs.html#B3F4BRFBRF21EF2EF13ER2F3R4E2
- Turkish carpet https://susam.net/cfrs.html#B11CF2R2F2R2FR6F2ER4ER2ER4ER2ER3ER3ER3ER3E3
- Shuriken https://susam.net/cfrs.html#BFR2BFBFBR2FBFBR2FBFBRFBFBFBFBF3E12

**Comment by aartaka** [comment]
Of course, you're free to use any of these on the demo page. The preferred name is `Artyom Bologov (aartaka)`.

**Comment by susam** [comment]
Thank you!
