### ISSUE TITLE
2 new demos

### ISSUE THREAD

**Issue by wong-justin** [susam/cfr#4]
Hello, thanks for making this fun project.

Here's what I have to share after noodling around for a couple of hours:

Circles (static)
https://susam.net/cfrs.html#B10F2R2FBR3E2FR2FB2R3EFR2F2EF2EF4R4E7F4R4E
<img width="283" alt="image" src="https://github.com/user-attachments/assets/cfa151c9-f6eb-45e6-8f65-20b14e4585c7">

Rectangle screensaver (dynamic)
https://susam.net/cfrs.html#RB24F2E7R2FBR3E3SE2CE3R2CE10
<img width="281" alt="image" src="https://github.com/user-attachments/assets/35a2e719-9e34-41c9-b2c3-85b48441ae5f">

**Comment by susam** [comment]
Thank you! Added these to <https://github.com/susam/cfrs/blob/main/demo.md>.
